name: check-build
run-name: ${{ github.actor }} is building this project
on: [push]
jobs:
  build-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm run bootstrap
      - run: npm run prebuild
      - run: npm run build --ignore-scripts
      - run: npm run build:e2e
